### ISSUE TITLE
Scrollbar behaviour during zoom

### ISSUE THREAD

**Issue by tk** [structurizr/ui#8]
If I zoom in my browsers (Firefox 110.0.1 (32-Bit), Chrome 110.0.5481.178) show two scrollbars (see attached screenshot).
1) For the area of the diagram
2) For the whole window
![grafik](https://user-images.githubusercontent.com/40080/223688449-d3e37554-3330-4196-930d-498c07078c1d.png)
This complicates the navigation in the diagram.

Adding `overflow:hidden;` to the [body CSS definition](https://github.com/structurizr/ui/blob/d0f87e7ee930905c3b7be5a714717dfdf9917797/src/css/structurizr.css#L1) fixes the problem, but reveals that the vertical scrollbar of the diagram area is not 100% visible.

**Comment by simonbrowndotje** [comment]
I can't reproduce this myself, but I suspect it's either something like a rounding error when calculating the viewport size, or it's a Windows specific thing (I'm on a Mac). Do you see the same issues with the example diagrams?

**Comment by tk** [comment]
Yes, I can reproduce it on my Windows machine:
![grafik](https://user-images.githubusercontent.com/40080/223766074-9802014b-20b5-469e-a0e1-a96a4f933196.png)

Box-Model Body:
![grafik](https://user-images.githubusercontent.com/40080/223766314-d01383b1-e3a1-4291-b86a-232cda27c12b.png)

Box-Model div id= "diagramNavigationPanel"
![grafik](https://user-images.githubusercontent.com/40080/223766949-f2441aab-18c0-43d4-bba6-0378e04f39f7.png)

Box-Model div Diagram area
![grafik](https://user-images.githubusercontent.com/40080/223767073-23f8da4d-fa89-48f0-ac73-016a994fe84b.png)

**Comment by simonbrowndotje** [comment]
Thanks for the into ... I think it's now resolved.

**Comment by tk** [comment]
Yes, thank you. I can confirm that it is gone for the example diagrams! 👍

**Comment by simonbrowndotje** [comment]
You're welcome! BTW, here's what scrollbars look like on the Mac:

![image](https://user-images.githubusercontent.com/1009874/223998249-9460f073-7810-46c1-9c26-4a9d9933cefe.png)

As you can see, they sit over the top of the content, and only show while scrolling ... i.e. they disappear within a couple of seconds when not being "used", which makes getting a screenshot pretty tricky! This makes for an interesting UX ("I didn't know this was scrollable because there are no scrollbars"), but a cleaner UI. This is why the issue didn't affect the Mac - the scrollbars don't take any additional pixels from the possible diagram width/height.
